### PR TITLE
re-add corpsepiece stuff to separate branch (gui/create-item corpsepiece spawning functionality)

### PR DESCRIPTION
**Pull request by ppaawwll**
there we go, all nice and clean in a separate branch after downloading the github desktop app

### CODE REVIEW

**Comment by ppaawwll** [comment]
fucking finally, there we go

**Comment by ppaawwll** [comment]
minor tweak

**Review by myk002 — APPROVED** [review]
I saw you had some recent questions on discord about body parts. are you still investigating anything or is this PR ready for merge?

**Comment by ppaawwll** [comment]
i think i'm ready to merge, ye!

there _are_ a few materials unaccounted for (like chitin, spit/tears/pus/blood, all appearing as "chops"), but i feel like enough have been covered for it to work for now and add those later if they're needed.

**Comment by myk002** [comment]
> i think i'm ready to merge, ye!
> 
> there _are_ a few materials unaccounted for (like chitin, spit/tears/pus/blood, all appearing as "chops"), but i feel like enough have been covered for it to work for now and add those later if they're needed.

SGTM. Thanks! Again, this is an impressive amount of work! corpsepiece generation has been a request for a **long** time.

**Pull request merged**
