### PR TITLE
Combine seeds dyes

### PR DESCRIPTION
**Pull request by silverflyone**
Version for review.
Contains: Ability to combine seeds and powders (dyes, flour). Excludes sand and plaster items. Ability to combine items in containers; so that seeds, powders and others are combined into containers (bags). Updated logging to include container changes.

### CODE REVIEW

**Comment by silverflyone** [comment]
@myk002 interested in your views. Is it worth asking others to help test?

**Comment by myk002** [comment]
I plan to feature this for testing in the beta release channel after we do our stable release this Friday. We should get lots of testing there : )

**Comment by silverflyone** [comment]
Awesome, the more the better. :)

A side effect of combining containers is that all types are included. It is QOL for seeds, dyes and flour, and I think also for the other types since it only applies to items already in containers. Thoughts? 

I'll have a look at doing bolts next; I'll raise another issue to track that one.

**Comment by silverflyone** [comment]
pre-commit.ci autofix

**Pull request closed without merging**
