### PR TITLE
You'd expect the web interface to be more convenient.

### PR DESCRIPTION
**Pull request by maxthyme**
Just confuses the shit out of me because I can't see a lot of the layout due to my userchrome and usercontent killing smashing the internet until it looks like I [think it should](http://i.imgur.com/7P8ZrVL.png
).

### CODE REVIEW

**Comment by lethosor** [comment]
@maxthyme did you turn on Travis in your fork? We're getting a lot of notifications in the DFHack IRC channel from your fork, and it's annoying.

**Comment by maxthyme** [comment]
Apparently I did, my bad, after that I got in a whole project of rebuilding my firefox shit to work with the new addon format and didn't even see these messages.

**Comment by ab9rf** [comment]
Generally speaking, you should not push new commits into a published branch until you've tested those commits locally. This is especially true for published branches that are the basis for a pull request, because GitHub will respawn precommit tests when a new commit is pushed to a published branch that is the basis of a pull request.

It's probably a best practice when you go to prep a pull request to create a new branch and push that branch to github, instead of basing your pull request from your sync of your generic 'master' or 'develop' branch. At least, that's what I (usually) do.

**Comment by lethosor** [comment]
I just realized that the testing scripts are part of the DFHack repo, which makes them harder to run if you just have the scripts repo checked out. I'll see if there's a way to improve that (even if you do check out the DFHack repo, there isn't an equivalent of travis/all.py there that works in the scripts repo).

**Pull request closed without merging**
