### PR TITLE
Change NEW_UNIT_ACTIVE to UNIT_NEW_ACTIVE in warn-stealers

### PR DESCRIPTION
**Pull request by wolfboyft**
Two pull requests overlapped

### CODE REVIEW

**Review by myk002 — APPROVED** [review]
D'oh! Also, could you add a changelog entry in the "Fixes" section for this?

**Comment by wolfboyft** [comment]
I always forget the changelog. Also, Lethsor asked me to check for all occurrences in the repo so I'll do that too.

**Comment by wolfboyft** [comment]
Done

**Comment by wolfboyft** [comment]
Oh I forgot to activate pre-commit on my clone

**Review by myk002 — APPROVED** [review]

**Comment by myk002** [comment]
> Oh I forgot to activate pre-commit on my clone

No worries - the pre-commit check in CI says it's good.

**Pull request merged**
