### PR TITLE
export identity information

### PR DESCRIPTION
**Pull request by robertjanetzko**
extends exportlegends.lua to export information about identities uses by historical figures

### CODE REVIEW

**Comment by JapaMala** [comment]
Those Anon values should never be used. Make a PR for df-structures first, to identify them, then use them in a script.

**Comment by robertjanetzko** [comment]
added pull request to df-structures: https://github.com/DFHack/df-structures/pull/244

**Comment by lethosor** [comment]
That was merged. Can you update the field name here (or I can push to your branch, I think, but I assume you have a better way of testing this than I do).

**Comment by lethosor** [comment]
Whoops, sorry for missing the update to this. Looks good to me.

**Pull request merged**
