### PR TITLE
fix to small issue in full-heal.lua

### PR DESCRIPTION
**Pull request by Amostubal**
there was a .job_type missing in line 151 causing it to throw errors.

### CODE REVIEW

**Comment by lethosor** [comment]
Does this actually work (the job-switching part)?

**Comment by Amostubal** [comment]
It was interesting as he just canceled the clean injury claiming to rest injury, but instead of actually switching to rest, he ran to hospital then went to work... I dropped a floor on him.

**Comment by lethosor** [comment]
I mean, I was more concerned about it breaking completely or crashing. What you described sounds better than that, and better than resting indefinitely, so it's fine with me.

**Comment by lethosor** [comment]
The build failure looks like my fault (I assumed that `probe` would be a valid link target, as practically every other plugin is, so I didn't bother to actually double-check that the docs built).

**Comment by Amostubal** [comment]
I've only tested it twice... on the same dwarf, on the same save... so I may drop a few more floors on some dwarfs and see if it does crash... if you want some more testing.

yeah I assumed it had to be another issue for travis, as I had only added the job_type into a line.

**Comment by Amostubal** [comment]
@lethosor well the only thing that did happen after dropping several more floors, I had one guy that continued to sit on his bed, listed as job clean self and refused to move, I had to manually switch him back to rest and let him sit a minute and he got up...

**Pull request merged**
