### PR TITLE
No need to lint turned-down ruby

### PR DESCRIPTION
**Pull request by hawkowl**
This removes the Ruby steps from the CI.

Not sure if this should go in after all of them are migrated, but while it was on my mind I opened a PR.

### CODE REVIEW

**Review by lethosor — APPROVED** [review]
Confirmed that there are no `*.rb` files on develop

**Comment by lethosor** [comment]
I was looking at the DFHack repo - didn't realize this was scripts.

This is definitely something we should do, but as a matter of principle, I think it should wait until there aren't any `*.rb` files left in this repo.

**Comment by myk002** [comment]
this is getting very close to being committed. just a few ruby scripts left

**Comment by myk002** [comment]
It's official! Ruby has been turned down. thanks!

**Pull request merged**
