### PR TITLE
Create uniteditor collection.

### PR DESCRIPTION
**Pull request by acattaneo88**
A collection of scripts to modify or reset the characteristics of a unit. You can alter attributes, skills, preferences, beliefs, goals and facets one at a time, or you can define a profile and apply it as a whole to the unit.

This collection exists for two reasons:
1. to group all the scripts with similar scopes in a single place, simplifying use and maintainability;
2. to increase the user-friendliness of the existing scripts by rewriting, reorganising and expanding their functionality.

The structure should be flexible enough to allow for more scripts to be added, and thus creating a suite of scripts to edit a unit (and to create a profile for it).

I created a dedicated folder to minimize the conflicts with the existing scripts and the current documentation builder. English is not my first language, but I tried to write clear and complete documentation. If anything is not clear, please ask.

The included profiles are just an example of what can be done, and I would appreciate your contribution in creating more profiles, maybe (just an idea) following one of the "starting builds" listed in the wiki.

### CODE REVIEW

**Comment by acattaneo88** [comment]
Ok, I have no idea how to fix this error:

> Warning, treated as error:
> ../../../dfhack/scripts/uniteditor/assign-attributes.lua:14: ERROR: Unexpected indentation.

**Comment by lethosor** [comment]
Why'd you close this? I can look into the Travis issue, but it's not particularly easy to do on mobile.

**Comment by acattaneo88** [comment]
It was a little bit messy. I'm going to reorganise things a little bit and then I will make a new pull request. Sorry about polluting the repo.

**Comment by lethosor** [comment]
Gotcha. A couple notes:

* Our documentation is all RST (not Markdown) so it would be nice if your docs could integrate into that somehow. Getting it all working requires the full DFHack repo and can be a bit tricky to set up, so I can help with that.
* The Travis error you got was related to this - I'm pretty sure the table [here](https://github.com/DFHack/scripts/pull/104/files#diff-f8811de8a351fbdb61da4e5912dc518dR15) needs a blank line before it. It looks like mostly valid RST otherwise, but you might need a blank line before bulleted lists too.
* Typically, subfolders in this repo are categories (GUI scripts, bugfixes, dev tools, mod tools). There's nothing _wrong_ with the way you've set things up, really, but it might be worth considering alternatives, such as subcommands of a single script (e.g. `unit-editor assign-attributes [args...]`). If you want to keep things in separate files, that's fine too (and it might be possible to have a single entrypoint script that calls out to separate files, but it'd take a bit of effort).

**Pull request closed without merging**
