### PR TITLE
Update make-legendary.lua

### PR DESCRIPTION
**Pull request by NotRexButCaesar**
MilitaryUnarmed is present in the classes, but was missing from this list.

### CODE REVIEW

**Review by myk002 — COMMENTED** [review]
Looks good! Could you add a changelog entry under "Fixes"?

**Review by myk002 — APPROVED** [review]

**Comment by NotRexButCaesar** [comment]
This was such a rapid response!

**Comment by myk002** [comment]
Merging. Be aware that since you committed to your master branch, things will need to get fixed on your fork before you can make other changes. It's better to make a branch for changes and submit a PR from that branch.

**Comment by NotRexButCaesar** [comment]
Oh, thank you for the advice: I do not use github very often, so I am not too familiar with all the different options.

**Comment by myk002** [comment]
> This was such a rapid response!

Thank you for such a beautifully simple and self-contained PR : )

**Pull request merged**
